[global]
directory = "/mnt/lol"
fstests = "/mnt/repos/fstests"
dry_run = false
# 72 hours
#duration = 259200
duration = 3600
umount_retries = 10
debug = true

[fsx]
procs = 8

[fsstress]
procs = 8

[btrfs]
#progs = "/mnt/repos/btrfs-progs"
progs = "/home/vmuser/btrfs-progs"
balance = true
reflink = false

[system]
drop_caches = false
